/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BLL.BanBLL;
import BLL.ChiTietHoaDonBLL;
import BLL.HoaDonBLL;
import BLL.LoaiBLL;
import BLL.TaiKhoanBLL;
import BLL.ThucUongBLL;
import DAL.TaiKhoanDAL;
import DTO.BanDTO;
import DTO.ChiTietHoaDonDTO;
import DTO.HoaDonDTO;
import DTO.LoaiDTO;
import DTO.TaiKhoanDTO;
import DTO.ThucUongDTO;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huyng
 */
public class HoaDonGUI extends javax.swing.JPanel {

    ArrayList<JButton> banButtons;

    /**
     * Creates new form TaiKhoanGUI
     */
    public HoaDonGUI() {
        initComponents();
        loadComboBox();
        layDanhSachBan();
    }

    private void layDanhSachBan() {
        jPanel1.setLayout(new GridLayout(4, 4));
         jPanel1.removeAll();
        banButtons = new ArrayList<>();
        List<BanDTO> ds = BanBLL.layDanhSachBan();
        for (BanDTO ban : ds) {
            JButton button = new JButton(ban.getTenBan());
            if ("Trống".equals(ban.getTrangThai())) {
                button.setBackground(Color.GREEN);
            } else {
                button.setBackground(Color.RED);
            }
            banButtons.add(button);

            button.addActionListener(e -> {
                loadDataToTable(ban.getMaBan());
                txtBan.setText(ban.getTenBan());
            });

        jPanel1.add(button);
        jPanel1.updateUI();
        jPanel1.revalidate();
        jPanel1.repaint();

        }
    }

    private void loadDataToTable(int maBan) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        model.setColumnCount(0);
        model.addColumn("ID");
        model.addColumn("Thức uống");
        model.addColumn("Số lượng");
        model.addColumn("Đơn giá");
         model.addColumn("Thành tiền");
        List<ChiTietHoaDonDTO> ds = BanBLL.layChiTietHoaDonChuaThanhToanCuaBan(maBan);
        long tongTien = 0;
        for (ChiTietHoaDonDTO chiTietHoaDon : ds) {
            long thanhTien = chiTietHoaDon.getSoLuong() * ThucUongBLL.timThucUongTheoMa(chiTietHoaDon.getMaThucUong()).getGia();
            tongTien += thanhTien;
            Object[] rowData = {chiTietHoaDon.getId(), ThucUongBLL.timThucUongTheoMa(chiTietHoaDon.getMaThucUong()).getTenThucUong(), chiTietHoaDon.getSoLuong(), ThucUongBLL.timThucUongTheoMa(chiTietHoaDon.getMaThucUong()).getGia(), thanhTien};
            model.addRow(rowData);
        }
        labelTongTien.setText("Tổng tiền: " + tongTien);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        txtGia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cboThucUong = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtBan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnThanhToan = new javax.swing.JButton();
        labelTongTien = new javax.swing.JLabel();

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        txtGia.setEditable(false);

        jLabel6.setText("Thức uống:");

        jLabel7.setText("Giá:");

        cboThucUong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboThucUong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboThucUongItemStateChanged(evt);
            }
        });

        jLabel3.setText("Bàn hiện tại:");

        txtBan.setEditable(false);

        jLabel8.setText("Số lượng:");

        txtSoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoLuongKeyReleased(evt);
            }
        });

        jLabel9.setText("Thành tiền:");

        txtThanhTien.setEditable(false);
        txtThanhTien.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(btnThem)
                            .addGap(27, 27, 27)
                            .addComponent(btnXoa))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGap(119, 119, 119)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cboThucUong, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtBan, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboThucUong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("HÓA ĐƠN");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách bàn"));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        labelTongTien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelTongTien.setText("Tổng tiền: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThanhToan)
                    .addComponent(labelTongTien))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        String tenBan = txtBan.getText();
        if (tenBan.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn bàn!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        HoaDonDTO ds = BanBLL.layHoaDonChuaThanhToanCuaBan(BanBLL.timBanTheoTen(tenBan).getMaBan());
        if (ds == null) {
            HoaDonDTO hoaDonDTO = new HoaDonDTO();
            hoaDonDTO.setMaBan(BanBLL.timBanTheoTen(tenBan).getMaBan());
            HoaDonBLL.themHoaDon(hoaDonDTO);
            BanBLL.capNhatTrangThai(BanBLL.timBanTheoTen(tenBan).getMaBan(), "Có người");
            layDanhSachBan();
            ChiTietHoaDonDTO chiTietHoaDonDTO = new ChiTietHoaDonDTO();
            chiTietHoaDonDTO.setMaHoaDon(BanBLL.layHoaDonChuaThanhToanCuaBan(BanBLL.timBanTheoTen(tenBan).getMaBan()).getMaHoaDon());
            int maThucUOng = ThucUongBLL.timThucUongTheoTen(cboThucUong.getSelectedItem().toString()).getMaThucUong();
            chiTietHoaDonDTO.setMaThucUong(maThucUOng);
            String soLuongText = txtSoLuong.getText();
            if (soLuongText.equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng!", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }
            int soLuong = Integer.parseInt(soLuongText);
            chiTietHoaDonDTO.setSoLuong(soLuong);
            if (ChiTietHoaDonBLL.themChiTietHoaDon(chiTietHoaDonDTO)) {
                JOptionPane.showMessageDialog(this, "Thêm chi tiết hóa đơn thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loadDataToTable(BanBLL.timBanTheoTen(tenBan).getMaBan());
                
            } else {
                JOptionPane.showMessageDialog(this, "Thêm chi tiết hóa đơn thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            ChiTietHoaDonDTO chiTietHoaDonDTO = new ChiTietHoaDonDTO();
            chiTietHoaDonDTO.setMaHoaDon(BanBLL.layHoaDonChuaThanhToanCuaBan(BanBLL.timBanTheoTen(tenBan).getMaBan()).getMaHoaDon());
            int maThucUOng = ThucUongBLL.timThucUongTheoTen(cboThucUong.getSelectedItem().toString()).getMaThucUong();
            chiTietHoaDonDTO.setMaThucUong(maThucUOng);
            String soLuongText = txtSoLuong.getText();
            if (soLuongText.equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng!", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }
            int soLuong = Integer.parseInt(soLuongText);
            chiTietHoaDonDTO.setSoLuong(soLuong);
            if (ChiTietHoaDonBLL.themChiTietHoaDon(chiTietHoaDonDTO)) {
                JOptionPane.showMessageDialog(this, "Thêm chi tiết hóa đơn thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loadDataToTable(BanBLL.timBanTheoTen(tenBan).getMaBan());
            } else {
                JOptionPane.showMessageDialog(this, "Thêm chi tiết hóa đơn thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
 // TODO add your handling code here:
 
        String tenBan = txtBan.getText();
        if (tenBan.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn bàn!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn tài khoản cần xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String id = model.getValueAt(selectedRow, 0).toString();

        int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn chi tiết hóa đơn này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {

            if (ChiTietHoaDonBLL.xoaChiTietHoaDon(Integer.parseInt(id))) {
                JOptionPane.showMessageDialog(this, "Xóa chi tiết hóa đơn thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loadDataToTable(BanBLL.timBanTheoTen(tenBan).getMaBan());
            } else {
                JOptionPane.showMessageDialog(this, "Xóa chi tiết hóa đơn thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed
    private void clear() {

    }
    private void loadComboBox() {
        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
        cboThucUong.setModel(comboBoxModel);
        List<ThucUongDTO> ds = ThucUongBLL.layDanhSachThucUong();
        for (ThucUongDTO thucUong : ds) {
            comboBoxModel.addElement(thucUong.getTenThucUong());
        }
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            String maThucUong = jTable1.getValueAt(selectedRow, 0).toString();
            String tenThucUong = jTable1.getValueAt(selectedRow, 1).toString();
            String loai = jTable1.getValueAt(selectedRow, 2).toString();

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void cboThucUongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboThucUongItemStateChanged
        // TODO add your handling code here:
        ThucUongDTO thucUongDTO = ThucUongBLL.timThucUongTheoTen(cboThucUong.getSelectedItem().toString());
        txtGia.setText(thucUongDTO.getGia() + "");
        txtThanhTien.setText("0");
        txtSoLuong.setText("");
    }//GEN-LAST:event_cboThucUongItemStateChanged

    private void txtSoLuongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoLuongKeyReleased
        // TODO add your handling code here:
        if (!"".equals(txtGia.getText()) && !"".equals(txtSoLuong.getText())) {

            txtThanhTien.setText((Integer.parseInt(txtSoLuong.getText()) * Long.parseLong(txtGia.getText())) + "");
        } else {
            txtThanhTien.setText("0");
        }
    }//GEN-LAST:event_txtSoLuongKeyReleased

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
         String tenBan = txtBan.getText();
        if (tenBan.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn bàn!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        HoaDonDTO hoaDonDTO = BanBLL.layHoaDonChuaThanhToanCuaBan(BanBLL.timBanTheoTen(tenBan).getMaBan());
        if (HoaDonBLL.suaHoaDon(hoaDonDTO)) {
                JOptionPane.showMessageDialog(this, "Thanh toán thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                 BanBLL.capNhatTrangThai(BanBLL.timBanTheoTen(tenBan).getMaBan(), "Trống");
            layDanhSachBan();
            }
        else{
          JOptionPane.showMessageDialog(this, "Thanh toán thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThanhToanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboThucUong;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelTongTien;
    private javax.swing.JTextField txtBan;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtThanhTien;
    // End of variables declaration//GEN-END:variables
}
