/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.BorderLayout;
import java.awt.FlowLayout;

/**
 *
 * @author huyng
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemTrangChu = new javax.swing.JMenuItem();
        menuItemThoat = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuItemTaiKhoan = new javax.swing.JMenuItem();
        menuItemBan = new javax.swing.JMenuItem();
        menuItemLoaiThucUong = new javax.swing.JMenuItem();
        menuItemThucUong = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemBanHang = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuItemChiTietHoaDon = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuItemThongKeTheoThucUong = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1029, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Trang chủ");

        menuItemTrangChu.setText("Trang chủ");
        jMenu1.add(menuItemTrangChu);

        menuItemThoat.setText("Thoát");
        jMenu1.add(menuItemThoat);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Danh mục");

        menuItemTaiKhoan.setText("Tài khoản");
        menuItemTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTaiKhoanActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemTaiKhoan);

        menuItemBan.setText("Bàn");
        menuItemBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBanActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemBan);

        menuItemLoaiThucUong.setText("Loại thức uống");
        menuItemLoaiThucUong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLoaiThucUongActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemLoaiThucUong);

        menuItemThucUong.setText("Thức uống");
        menuItemThucUong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemThucUongActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemThucUong);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Giao dịch");

        menuItemBanHang.setText("Bán hàng");
        menuItemBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBanHangActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemBanHang);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Lịch sử");

        menuItemChiTietHoaDon.setText("Chi tiết hóa đơn");
        menuItemChiTietHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemChiTietHoaDonActionPerformed(evt);
            }
        });
        jMenu5.add(menuItemChiTietHoaDon);

        jMenuBar1.add(jMenu5);

        jMenu7.setText("Thống kê");

        menuItemThongKeTheoThucUong.setText("Theo thức uống");
        menuItemThongKeTheoThucUong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemThongKeTheoThucUongActionPerformed(evt);
            }
        });
        jMenu7.add(menuItemThongKeTheoThucUong);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTaiKhoanActionPerformed
        // TODO add your handling code here:
        TaiKhoanGUI gui = new TaiKhoanGUI();
        gui.setVisible(true);
        jPanel1.setLayout(new FlowLayout());
        jPanel1.removeAll();
        jPanel1.add(gui, BorderLayout.CENTER);
        jPanel1.updateUI();

        // Cập nhật lại giao diện
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_menuItemTaiKhoanActionPerformed

    private void menuItemBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBanActionPerformed
        // TODO add your handling code here:
          BanGUI gui = new BanGUI();
        gui.setVisible(true);
        jPanel1.setLayout(new FlowLayout());
        jPanel1.removeAll();
        jPanel1.add(gui, BorderLayout.CENTER);
        jPanel1.updateUI();

        // Cập nhật lại giao diện
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_menuItemBanActionPerformed

    private void menuItemLoaiThucUongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLoaiThucUongActionPerformed
        // TODO add your handling code here:
         LoaiGUI gui = new LoaiGUI();
        gui.setVisible(true);
        jPanel1.setLayout(new FlowLayout());
        jPanel1.removeAll();
        jPanel1.add(gui, BorderLayout.CENTER);
        jPanel1.updateUI();

        // Cập nhật lại giao diện
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_menuItemLoaiThucUongActionPerformed

    private void menuItemThucUongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemThucUongActionPerformed
        // TODO add your handling code here:
           ThucUongGUI gui = new ThucUongGUI();
        gui.setVisible(true);
        jPanel1.setLayout(new FlowLayout());
        jPanel1.removeAll();
        jPanel1.add(gui, BorderLayout.CENTER);
        jPanel1.updateUI();

        // Cập nhật lại giao diện
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_menuItemThucUongActionPerformed

    private void menuItemBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBanHangActionPerformed
        // TODO add your handling code here:
            HoaDonGUI gui = new HoaDonGUI();
        gui.setVisible(true);
        jPanel1.setLayout(new FlowLayout());
        jPanel1.removeAll();
        jPanel1.add(gui, BorderLayout.CENTER);
        jPanel1.updateUI();

        // Cập nhật lại giao diện
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_menuItemBanHangActionPerformed

    private void menuItemChiTietHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemChiTietHoaDonActionPerformed
        // TODO add your handling code here:
            ChiTietHoaDonGUI gui = new ChiTietHoaDonGUI();
        gui.setVisible(true);
        jPanel1.setLayout(new FlowLayout());
        jPanel1.removeAll();
        jPanel1.add(gui, BorderLayout.CENTER);
        jPanel1.updateUI();

        // Cập nhật lại giao diện
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_menuItemChiTietHoaDonActionPerformed

    private void menuItemThongKeTheoThucUongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemThongKeTheoThucUongActionPerformed
        // TODO add your handling code here:
                ThongKeTheoThucUongGUI gui = new ThongKeTheoThucUongGUI();
        gui.setVisible(true);
        jPanel1.setLayout(new FlowLayout());
        jPanel1.removeAll();
        jPanel1.add(gui, BorderLayout.CENTER);
        jPanel1.updateUI();

        // Cập nhật lại giao diện
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_menuItemThongKeTheoThucUongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuItemBan;
    private javax.swing.JMenuItem menuItemBanHang;
    private javax.swing.JMenuItem menuItemChiTietHoaDon;
    private javax.swing.JMenuItem menuItemLoaiThucUong;
    private javax.swing.JMenuItem menuItemTaiKhoan;
    private javax.swing.JMenuItem menuItemThoat;
    private javax.swing.JMenuItem menuItemThongKeTheoThucUong;
    private javax.swing.JMenuItem menuItemThucUong;
    private javax.swing.JMenuItem menuItemTrangChu;
    // End of variables declaration//GEN-END:variables
}
